.. change::
    :tags: bug, orm, py3k
    :tickets: 4990

    Fixed issue where when assigning a collection to itself as a slice, the
    mutation operation would fail as it would first erase the assigned
    collection inadvertently.   As an assignment that does not change  the
    contents should not generate events, the operation is now a no-op. Note
    that the fix only applies to Python 3; in Python 2, the ``__setitem__``
    hook isn't called in this case; ``__setslice__`` is used instead which
    recreates the list item-by-item in all cases.